name: xchain_cosmos_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none # Remove this line if you wish to publish to pub.dev
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  xchain_utils:
    path: ../xchain_utils
  xchain_client:
    path: ../xchain_client

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.6

resolution: workspace
